### ISSUE TITLE
Domain create method throws error

### ISSUE THREAD

**Issue by haisham** [InterNetX/php-domainrobot-sdk#22]
Although domain registration goes fine, but the following error is being thrown which prevents further execution of the script:

`Uncaught Exception TypeError: "Argument 1 passed to Domainrobot\Model\Job::__construct() must be of the type array or null, int is given"`

upon debugging in SDK i found the following line is the problem             
https://github.com/InterNetX/php-domainrobot-sdk/blob/174ba5d9209e89d4e2046062baa4ea44936edeba/src/Service/DomainService.php#L41

**Comment by ChripIX** [comment]
Hello,
could you please provide us with more Information ?
An example of the Script which leads to the Exception would help us a lot to discover the Problem.

Greetings
Chris

**Comment by ChripIX** [comment]
Hello again,
you don't need to provide an Example anymore, we fixed the Issue already.
There is a new Version 0.7.4 of the SDK available where the Bug is fixed.

Greetings 
Chris
