### ISSUE TITLE
Zone Resource Records incomplete

### ISSUE THREAD

**Issue by adrzei** [InterNetX/php-domainrobot-sdk#32]
It seems that since version 0.8.0 the zone data is incomplete. I always get only one entry back here. If I use my previous version 0.5.2, the results are correct.

**Comment by ChripIX** [comment]
Hello,
i am looking into this Issue.
Could you please provide more information ?
Do you mean the Task of listing multiple Zones (/zone/_search) or do you mean the Task of getting the Data of one specific Zone (​/zone​/{name}​/{systemNameServer}) ?

**Comment by ChripIX** [comment]
Despite don't comprehending your question fully yet, i looked into the Zone Service nonetheless and tested a little bit.
I found an bug with the Zone Info Task which i updated an pushed into the repository.
Please pull the changes into your repository and try if the issue is resolved.

**Comment by JZubero** [comment]
@chris-pleint This still seems to be an issue. Experiencing the same problem when using `dev-master` / `0.8.1`.

**Comment by ChripIX** [comment]
Could you then provide an basic example of the problem, please ?

**Comment by JZubero** [comment]
Sure, thanks for following up.

I want to request the data for my zone `classiconn.com`:

```php
$this->domainrobot->zone->info('classiconn.com', 'a.ns14.net')
```

(`$this->domainrobot` holds a standard Domainrobot instance).

For this command, I receive the following results (just an excerpt):

![Bildschirmfoto-20210208123220-536x394](https://user-images.githubusercontent.com/13751426/107214514-4c76bf80-6a0a-11eb-93f6-980c61417ec4.png)

So only 1 resource record is showing. By looking at the AutoDNS UI, it is clear, that only the first record is being delivered (framed in yellow):

![Screenshot](https://user-images.githubusercontent.com/13751426/107214600-67e1ca80-6a0a-11eb-8655-d027b0c0ec0c.png)

Do you need any more information for your investigation?

**Comment by ChripIX** [comment]
Thank you very much for this information. We will look into this issue and come back to you shortly.

**Comment by JZubero** [comment]
You're welcome. For my use case, I have to update a zone's resource records. Since `$domainrobot->zone->update()` seems to be a hard setter for the fields provided, grabbing the existing resource records first, is mandatory.

**Comment by ChripIX** [comment]
I looked into the issue and because you provided much information i found the bug which caused that problem.
A new version was released, please update the SDK and look if now everything works like expected.

**Comment by JZubero** [comment]
Sweet! This was fast. Just tested the patch and I can confirm that it does the trick :clap: Thanks!

By looking at your commit, I can see that the fix was beneficial for some other code fragments as well?

I have noticed tags 0.8.1 and 0.8.2 did not get published on your [Packagist](https://packagist.org/packages/internetx/php-domainrobot-sdk). Maybe a broken automation?

**Comment by ChripIX** [comment]
Nice that now everything works as expected !

Yes the patch affects all models, because we are creating the files automated with our swagger codegenerator.

Because i forgot to change the version in composer.json releases 0.8.1 and 0.8.2 are not in Packagist.

I made release 0.8.3 and that one is now in Packagist.

**Comment by JZubero** [comment]
OK, I'd say we are all set then. Thanks again for quick reaction :+1:

**Comment by ChripIX** [comment]
You are welcome, glad i could help !
