### ISSUE TITLE
Class "Domainrobot\Service\DomainCancelation" not found

### ISSUE THREAD

**Issue by peterhagel** [InterNetX/php-domainrobot-sdk#39]
Hi,

wenn ich versuche die $domainrobot->domain->cancelationList aufzurufen, erhalte ich folgenden fehler:

`
Class "Domainrobot\Service\DomainCancelation" not found

  at vendor/internetx/php-domainrobot-sdk/src/Service/DomainService.php:345
    341▕         $data = $domainrobotResult->getResult()['data'];
    342▕ 
    343▕         $domainCancelations = array();
    344▕         foreach ($data as $d) {
  ➜ 345▕             $dc = new DomainCancelation($d);
    346▕             array_push($domainCancelations, $dc);
    347▕         }
    348▕ 
    349▕         return $domainCancelations;
`

**Comment by ChripIX** [comment]
Hi,
thanks for your message.

Please update to the new version, the fix for the error was already in the master branch, but no new release for the SDK was yet created.

Sincerly,
Chris
